plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.trknpedometer'
version = '0.1.0'

android {
  namespace "expo.modules.trknpedometer"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation 'androidx.work:work-runtime-ktx:2.8.1'
  implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4'
}
